<a href="https://colab.research.google.com/github/623020514-5/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np #เพื่อสำหรับใช้งานกับข้อมูลที่เป็นตัวเลข (อยู่ในรูป matrix)

#**Numpy Array**

สร้าง Numpy Array

In [28]:
np_a = np.array([[1,2,3],[4,5,6]])

In [29]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np_a.shape

(2, 3)

In [31]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

matrix transpose

In [32]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

สร้าง matrix เริ่มต้น (zeros,ones)

In [33]:
np_z = np.zeros((4,5))  
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [35]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

สร้าง matrix random ค่าเเบบมั่ว ๆ

In [36]:
np.random.randn(5,5) 
# randn คือ random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[ 2.01350291,  0.4045146 ,  0.24719093,  0.75184412,  0.61265302],
       [ 0.29448181,  0.7569065 ,  1.44644   , -0.42954473, -0.10301093],
       [-0.33170438, -1.24528897, -1.52705403, -0.77564861, -0.3490183 ],
       [ 0.46100815, -0.90104707,  1.65309244, -0.55461412, -1.37474101],
       [-0.26524483,  1.23279202, -0.19209718,  0.25277049,  0.02938321]])

In [37]:
2+(5*np.random.randn(3,3)) 
# random เลขมาจาก normal distribution ที่มี mu=2 std=5

array([[-0.21001449,  3.74940936,  2.25263083],
       [ 2.09826771,  1.13719215,  4.10321309],
       [-1.0910111 ,  6.12466524,  6.03806084]])

In [38]:
np.random.randint(5,11,(4,5))
# random เลขจำนวนเต็ม ค่าตั้งเเต่ระหว่าง 5 ถึง 10 (5,11,(ขนาด 4x5))

array([[ 8,  5,  7,  5,  8],
       [ 8, 10,  7,  9,  5],
       [ 8,  8,  5,  9,  5],
       [ 7,  8,  5, 10,  7]])

matrix properties

In [39]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np_a.T #transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [41]:
1+np_a #add Scalar to matrix

array([[2, 3, 4],
       [5, 6, 7]])

In [42]:
2*np_a #multiply scalar to matrix

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [43]:
np_c = np.array([[6,5,4],[3,2,1]])
np_c

array([[6, 5, 4],
       [3, 2, 1]])

In [44]:
np_a + np_c #adding matrix to matrix
#การบวกระหว่างเมททริกซ์ปกติ

array([[7, 7, 7],
       [7, 7, 7]])

In [45]:
np_a.shape #ดูขนาด

(2, 3)

In [46]:
np_c.shape

(2, 3)

จากการตรวจสอบขนาดของเมทริกซ์ทั้งสองจะเห็นว่ามีขนาดที่เหมือนกันดังนั้นจะเอามาคูณกันเลยไม่ได้จะต้องเอาเมททริกซ์อันใดอันนึงไป ทรานสโพสก่อน โดยการ .T

In [47]:
np.dot(np_a,np_c.T) #multipling matrix to matrix (a,b)x(b,c)=(a,c)

array([[28, 10],
       [73, 28]])

##Indexing & Slicing
 ชี้ยังไง

In [48]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np_a[1,1]

5

In [50]:
np_a[:2,:2]

array([[1, 2],
       [4, 5]])

In [51]:
np_a[0,:]

array([1, 2, 3])

##Useful functions

In [56]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.sum(np_a)

21

In [57]:
np.sum(np_a,axis=0)  # axis 0 ก็คือรวมเลขในแต่ละแถว

array([5, 7, 9])

In [58]:
np.sum(np_a,axis=1)  # axis 1 ก็คือรวมเลขในแต่ละหลัก

array([ 6, 15])

In [60]:
np.mean(np_a)

3.5

In [61]:
np.mean(np_a,axis=0)  #หา mean ของ column

array([2.5, 3.5, 4.5])

#วนลูปเอง

**summation**

In [52]:
np_a.shape

(2, 3)

np.sum(np_a)

In [53]:
sum_all = 0

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all = sum_all + np_a[row,col]
        print(f'we are at row={row},col={col} np_a[{row},{col}]={np_a[row,col]}  sum_all={sum_all}')
print(sum_all)

we are at row=0,col=0 np_a[0,0]=1  sum_all=1
we are at row=0,col=1 np_a[0,1]=2  sum_all=3
we are at row=0,col=2 np_a[0,2]=3  sum_all=6
we are at row=1,col=0 np_a[1,0]=4  sum_all=10
we are at row=1,col=1 np_a[1,1]=5  sum_all=15
we are at row=1,col=2 np_a[1,2]=6  sum_all=21
21


np.sum(np_a,axis=0)

In [54]:
sum_all = np.zeros(np_a.shape[1])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[col] = sum_all[col] + np_a[row,col]
print(sum_all)

[5. 7. 9.]


Quiz กลุ่ม

วนลูปหาค่า

*   np.sum(np_a,axis=1)
*   np.mean(np_a)
*   np.mean(np_a,axis=0)
*   np.mean(np_a,axis=1)


In [55]:
mean_all = np.zeros(np_a.shape[1])
for row in range(np_a.shape[0]):
     for col in range(np_a.shape[1]):
          mean_all[col] = mean_all[col] + np_a[row,col]/2
print(mean_all)

[2.5 3.5 4.5]
