<a href="https://colab.research.google.com/github/623020514-5/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np #เพื่อสำหรับใช้งานกับข้อมูลที่เป็นตัวเลข (อยู่ในรูป matrix)

#**Numpy Array**

สร้าง Numpy Array

In [3]:
np_a = np.array([[1,2,3],[4,5,6]])

In [4]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np_a.shape

(2, 3)

In [6]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

matrix transpose

In [7]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

สร้าง matrix เริ่มต้น (zeros,ones)

In [8]:
np_z = np.zeros((4,5))  
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

สร้าง matrix random ค่าเเบบมั่ว ๆ

In [11]:
np.random.randn(5,5) 
# randn คือ random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[-0.44573413, -0.88421328, -0.71439697,  0.97722851,  1.02984926],
       [-1.47212539,  0.7603073 ,  0.6062681 , -0.62854439,  0.26163585],
       [ 0.14396381, -0.8969371 ,  1.13623713, -0.67185212, -0.72601383],
       [-1.51859917,  0.49148761, -0.90400641,  0.00472482, -0.6882997 ],
       [-0.13696226,  0.22122596, -0.02499671,  0.71950055,  0.49450663]])

In [12]:
2+(5*np.random.randn(3,3)) 
# random เลขมาจาก normal distribution ที่มี mu=2 std=5

array([[ 2.70653676,  0.11553406, -8.28938204],
       [-1.73820512,  4.16837468,  9.97768548],
       [-0.72186467, -1.58811462,  4.4497054 ]])

In [13]:
np.random.randint(5,11,(4,5))
# random เลขจำนวนเต็ม ค่าตั้งเเต่ระหว่าง 5 ถึง 10 (5,11,(ขนาด 4x5))

array([[ 7,  8,  8, 10, 10],
       [ 8,  7,  9,  5,  8],
       [ 7,  9,  7,  8,  7],
       [ 9,  8,  8,  9,  9]])

matrix properties

In [14]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np_a.T #transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
1+np_a #add Scalar to matrix

array([[2, 3, 4],
       [5, 6, 7]])

In [17]:
2*np_a #multiply scalar to matrix

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [18]:
np_c = np.array([[6,5,4],[3,2,1]])
np_c

array([[6, 5, 4],
       [3, 2, 1]])

In [20]:
np_a + np_c #adding matrix to matrix
#การบวกระหว่างเมททริกซ์ปกติ

array([[7, 7, 7],
       [7, 7, 7]])

In [21]:
np_a.shape #ดูขนาด

(2, 3)

In [22]:
np_c.shape

(2, 3)

จากการตรวจสอบขนาดของเมทริกซ์ทั้งสองจะเห็นว่ามีขนาดที่เหมือนกันดังนั้นจะเอามาคูณกันเลยไม่ได้จะต้องเอาเมททริกซ์อันใดอันนึงไป ทรานสโพสก่อน โดยการ .T

In [24]:
np.dot(np_a,np_c.T) #multipling matrix to matrix (a,b)x(b,c)=(a,c)

array([[28, 10],
       [73, 28]])

##Indexing & Slicing
 ชี้ยังไง

In [25]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np_a[1,1]

5